DROP DATABASE IF EXISTS betterhelp;
CREATE DATABASE betterhelp DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON betterhelp.* TO bh_user@localhost IDENTIFIED BY 'password';
