USE betterhelp;

DROP TABLE IF EXISTS survey;
CREATE TABLE survey (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS questions;
CREATE TABLE questions (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sid INT(6) UNSIGNED,
    name VARCHAR(255) NOT NULL,
    answ_type INT(6) UNSIGNED NOT NULL,
    order_of INT(6) UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS answers;
CREATE TABLE answers (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    qid INT(6) UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    order_of INT(6) UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS entries;
CREATE TABLE entries (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    aid INT(6) UNSIGNED NOT NULL,
    answer VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL 
);
